build:
    nodes:
        analysis:
            project_setup:
                override:
                - 'true'
            tests:
                override:
                - php-scrutinizer-run
                -   command: phpcs-run
                    use_website_config: true
        tests: true
filter:
    excluded_paths:
    - 'tests/*'
checks:
    php: true
tools:
    php_sim: true
    php_pdepend: true
    php_analyzer: true
    external_code_coverage: true