build:
    nodes:
        analysis:
            project_setup:
                override:
                -   'true'
            tests:
                override:
                -   php-scrutinizer-run
                -   command: phpcs-run
                    use_website_config: true
        tests: true
        coverage:
            tests:
                override:
                -   command: ./vendor/bin/phpunit --configuration=phpunit.xml
                    coverage:
                        file: coverage.xml
                        format: clover
filter:
    excluded_paths:
    -   'tests/*'
checks:
    php: true
tools:
    php_sim: true
    php_pdepend: true
    php_analyzer: true